title = "Jaylen's TweenModule Documentation" 
GitRepoUrl = "https://github.com/jvqze/Jaylen-TweenModule"
gitSourceBranch = "master"

[home]
enabled = true
includeReadme = true

[docusaurus]
favicon = "https://us-east-1.tixte.net/uploads/cdn.jaylen.nyc/TweenModuleImage.png"

url = "https://jvqze.github.io"
baseUrl = "/Jaylen-TweenModule"

[footer]
style = "dark"