title = "Jaylen's TweenModule Documentation" 
GitRepoUrl = "https://github.com/jvqze/Jaylen-TweenModule"
gitSourceBranch = "master"

[home]
enabled = true
includeReadme = true

[docusaurus]
favicon = "https://us-east-1.tixte.net/uploads/cdn.jaylen.nyc/TweenModuleImage.png"

[footer]
style = "dark"